import { timestamp, uuid } from "drizzle-orm/pg-core";

/** Primary key: UUID v7-compatible random UUID generated by Postgres. */
export const id = () => uuid().primaryKey().defaultRandom();

/** `created_at` / `updated_at` pair used by most tables. */
export const timestamps = {
  createdAt: timestamp({ withTimezone: true }).notNull().defaultNow(),
  updatedAt: timestamp({ withTimezone: true })
    .notNull()
    .defaultNow()
    .$onUpdate(() => new Date()),
};
