// Regenerates docs/tickets/BOARD.md from the ticket files.
// Fails (exit 1) on malformed tickets so CI catches them.
import { readdirSync, readFileSync, writeFileSync } from "node:fs";
import { join } from "node:path";

const ROOT = join(import.meta.dirname, "..", "docs", "tickets");
const STATUSES = ["in-progress", "in-review", "todo", "backlog", "done", "wont-do"];
const TYPES = ["epic", "story", "task", "bug", "spike"];
const errors = [];

function parse(file) {
  const text = readFileSync(file, "utf8");
  const m = /^---\r?\n([\s\S]*?)\r?\n---/.exec(text);
  if (!m) {
    errors.push(`${file}: missing front-matter`);
    return null;
  }
  const meta = {};
  for (const line of m[1].split(/\r?\n/)) {
    const i = line.indexOf(":");
    if (i < 0) continue;
    let v = line.slice(i + 1).trim();
    if (v.startsWith("[") && v.endsWith("]"))
      v = v
        .slice(1, -1)
        .split(",")
        .map((s) => s.trim())
        .filter(Boolean);
    else if (v.startsWith('"')) v = JSON.parse(v);
    meta[line.slice(0, i).trim()] = v;
  }
  const ac = (text.match(/^- \[[ x]\]/gm) || []).length;
  const acDone = (text.match(/^- \[x\]/gm) || []).length;
  return { ...meta, ac, acDone };
}

const epics = readdirSync(join(ROOT, "epics"))
  .filter((f) => f.endsWith(".md"))
  .map((f) => parse(join(ROOT, "epics", f)))
  .filter(Boolean);
const issues = readdirSync(ROOT)
  .filter((f) => /^OL-\d+\.md$/.test(f))
  .map((f) => parse(join(ROOT, f)))
  .filter(Boolean);

const keys = new Set([...epics, ...issues].map((t) => t.key));
for (const t of [...epics, ...issues]) {
  if (!t.key) errors.push(`ticket without key: ${t.title}`);
  if (!STATUSES.includes(t.status)) errors.push(`${t.key}: unknown status "${t.status}"`);
  if (!TYPES.includes(t.type)) errors.push(`${t.key}: unknown type "${t.type}"`);
  for (const d of [].concat(t.depends_on || []))
    if (!keys.has(d)) errors.push(`${t.key}: depends on unknown ${d}`);
  if (t.type !== "epic" && !keys.has(t.epic)) errors.push(`${t.key}: unknown epic ${t.epic}`);
  if (t.status === "done" && t.ac !== t.acDone)
    errors.push(`${t.key}: status done but ${t.ac - t.acDone} acceptance criteria unchecked`);
}
if (errors.length) {
  console.error(errors.join("\n"));
  process.exit(1);
}

const num = (k) => Number(k.split("-").pop().replace("E", ""));
const byKey = (a, b) => num(a.key) - num(b.key);
const done = issues.filter((t) => t.status === "done");
const pts = (list) => list.reduce((s, t) => s + Number(t.points || 0), 0);

let out = `# Board\n\n_Generated by \`node scripts/tickets-board.mjs\`. Do not edit by hand._\n\n`;
out += `**${done.length}/${issues.length} issues done · ${pts(done)}/${pts(issues)} points**\n\n`;
for (const s of STATUSES) {
  const list = issues.filter((t) => t.status === s).sort(byKey);
  if (!list.length) continue;
  out += `## ${s} (${list.length})\n\n| Key | Title | Epic | Priority | Pts | Release | AC |\n|---|---|---|---|---|---|---|\n`;
  for (const t of list)
    out += `| [${t.key}](${t.key}.md) | ${t.title} | ${t.epic} | ${t.priority} | ${t.points} | ${t.release} | ${t.acDone}/${t.ac} |\n`;
  out += "\n";
}
out += `## Epics\n\n| Key | Title | Release | Status | Issues done | Points done |\n|---|---|---|---|---|---|\n`;
for (const e of epics.sort(byKey)) {
  const kids = issues.filter((t) => t.epic === e.key);
  const kd = kids.filter((t) => t.status === "done");
  out += `| [${e.key}](epics/${e.key}.md) | ${e.title} | ${e.release} | ${e.status} | ${kd.length}/${kids.length} | ${pts(kd)}/${pts(kids)} |\n`;
}
writeFileSync(join(ROOT, "BOARD.md"), out);
console.log(`board: ${issues.length} issues, ${epics.length} epics`);
