// One-off generator: writes the initial epics and tickets from the plan below.
// Run once (`node scripts/tickets-gen.mjs`); after that, tickets are edited by hand.
import { mkdirSync, writeFileSync, existsSync } from "node:fs";
import { join } from "node:path";

const ROOT = join(import.meta.dirname, "..", "docs", "tickets");
const TODAY = new Date().toISOString().slice(0, 10);

const epics = [
  [
    "OL-E1",
    "Open-source foundation",
    "R0",
    "Licence, repository layout, tooling, CI quality gates, contribution files, Docker Compose stack, ticket system.",
  ],
  [
    "OL-E2",
    "Core platform",
    "R1",
    "Organisations, users, authentication, roles and permissions, projects, audit log.",
  ],
  [
    "OL-E3",
    "Assets and storage",
    "R1",
    "Upload, content hashing, storage adapter (local disk and S3/MinIO), signed media URLs, bulk import.",
  ],
  [
    "OL-E4",
    "Taxonomy",
    "R1",
    "Versioned label sets with descriptions, guidelines, examples, attributes and validation rules.",
  ],
  [
    "OL-E5",
    "Document/OCR labelling",
    "R1",
    "Canvas editor with layers, word/line boxes, non-text regions, flags, relations, ignore regions, pre-labelling, queues and review.",
  ],
  [
    "OL-E6",
    "Snapshots and adapters",
    "R1",
    "Frozen dataset snapshots and the exporter, destination, launcher and tracker adapter framework.",
  ],
  [
    "OL-E7",
    "OCR evaluation",
    "R1",
    "Canonical OCR contract, engine adapters, matcher, metrics, leaderboard, slices, error explorer, regression gate.",
  ],
  [
    "OL-E8",
    "Public API and integrations",
    "R1",
    "Versioned REST API, OpenAPI, API keys, rate limits, webhooks, SDKs.",
  ],
  [
    "OL-E9",
    "Work management and quality",
    "R1",
    "Assignment, queues, progress dashboards, comments, notifications, gold sets, consensus.",
  ],
  ["OL-E10", "Additional modalities", "R2", "LLM data, audio, vision breadth, video, text/NLP plugins."],
];

// [key, type, title, epic, priority, points, release, labels, depends_on, description, acceptance[], notes]
const T = [
  // ---- E1 foundation
  [
    "OL-1",
    "task",
    "Repository foundation and open-source files",
    "OL-E1",
    "highest",
    3,
    "R0",
    ["infra", "docs"],
    [],
    "Create the monorepo skeleton and the files every open-source project needs.",
    [
      "Apache-2.0 `LICENSE` (official text) and `NOTICE` present",
      "`README.md` explains what OpenLabel is, the status, and how to run it locally",
      "`CONTRIBUTING.md` (DCO sign-off, Conventional Commits, branch naming, ticket workflow)",
      "`CODE_OF_CONDUCT.md` (Contributor Covenant 2.1), `SECURITY.md` (private disclosure), `GOVERNANCE.md`, `CHANGELOG.md`",
      "Issue and PR templates under `.github/`",
      "`docs/architecture.md` committed with its diagrams",
      "`.editorconfig`, `.gitattributes` (LF line endings), `.gitignore`",
    ],
    "Line endings forced to LF via .gitattributes so shell scripts work in Linux containers built on Windows hosts.",
  ],
  [
    "OL-2",
    "task",
    "Ticket tracker in the repository",
    "OL-E1",
    "highest",
    2,
    "R0",
    ["docs", "infra"],
    [],
    "Jira-style tickets as Markdown files with YAML front-matter, plus a generated board.",
    [
      "Conventions documented in `docs/tickets/README.md`",
      "Every epic and R0/R1 ticket exists as a file",
      "`scripts/tickets-board.mjs` regenerates `BOARD.md` grouped by status and epic",
      "Board script fails loudly on invalid front-matter (unknown status, missing key)",
    ],
    "",
  ],
  [
    "OL-3",
    "task",
    "Workspace tooling: pnpm, Turborepo, TypeScript, lint, format",
    "OL-E1",
    "highest",
    3,
    "R0",
    ["infra"],
    ["OL-1"],
    "pnpm workspaces with Turborepo, shared strict TypeScript config, ESLint and Prettier.",
    [
      "`pnpm install` works from a clean clone",
      "`pnpm lint`, `pnpm typecheck`, `pnpm test`, `pnpm build` run across all packages via Turborepo",
      "Shared `tsconfig.base.json` with `strict`, `noUncheckedIndexedAccess`, `exactOptionalPropertyTypes`",
      "ESLint flat config with typescript-eslint strict rules; Prettier config",
      "Node version pinned (`.nvmrc` and `engines`)",
    ],
    "TypeScript pinned to the newest version supported by typescript-eslint (currently <6.1).",
  ],
  [
    "OL-4",
    "task",
    "Docker Compose stack: app, worker, Postgres, MinIO",
    "OL-E1",
    "highest",
    5,
    "R0",
    ["infra"],
    ["OL-3"],
    "One command brings up the whole platform locally and on a single server.",
    [
      "`docker compose up -d` starts web, worker, postgres and minio",
      "Postgres and MinIO have health checks; web and worker wait for them",
      "Data persisted in named volumes",
      "MinIO bucket created automatically on first start",
      "Web reachable on a configurable port; `/api/health` returns 200 with DB and storage status",
      "Multi-stage Dockerfile; runtime image runs as non-root; no dev dependencies in the final image",
      "`.env.example` documents every variable; no secrets committed",
    ],
    "",
  ],
  [
    "OL-5",
    "task",
    "Contracts package: zod schemas as the single source of truth",
    "OL-E1",
    "high",
    3,
    "R0",
    ["backend"],
    ["OL-3"],
    "`@openlabel/contracts` holds the shared schemas: config, API errors, region shapes, canonical OCR result.",
    [
      "Environment config schema validated at start-up with readable errors",
      "RFC 9457 problem-details error schema and helper",
      "Region schemas: box, polygon, OCR word/line, non-text region, flags, relations",
      "Canonical OCR result schema (architecture section 12.1)",
      "Unit tests for valid and invalid examples of every schema",
    ],
    "",
  ],
  [
    "OL-6",
    "task",
    "CI pipeline",
    "OL-E1",
    "high",
    3,
    "R0",
    ["infra", "security"],
    ["OL-3"],
    "GitHub Actions run every quality gate on pull requests.",
    [
      "Lint, typecheck, unit tests, build on every PR",
      "Docker image build",
      "Dependency audit and licence check (permissive licences only in core)",
      "Secret scanning",
      "DCO sign-off check",
    ],
    "",
  ],
  [
    "OL-7",
    "task",
    "Database package: Drizzle schema, migrations, client",
    "OL-E1",
    "highest",
    5,
    "R0",
    ["backend", "db"],
    ["OL-3", "OL-5"],
    "`@openlabel/db` with the initial schema and migration tooling.",
    [
      "Drizzle schema for organisations, users, memberships, projects, assets, audit_events",
      "Migrations generated and applied with `pnpm db:migrate`; worker/web run pending migrations on start",
      "Every tenant table has `org_id`; indexes on foreign keys",
      "Typed client factory with connection pooling",
      "Integration test runs migrations against a real Postgres",
    ],
    "",
  ],

  // ---- E2 core platform
  [
    "OL-8",
    "story",
    "Authentication: email/password, sessions, MFA",
    "OL-E2",
    "highest",
    8,
    "R1",
    ["backend", "security"],
    ["OL-7"],
    "Users sign up and sign in; admins can require two-factor authentication.",
    [
      "Email + password sign-up/sign-in (argon2 hashing)",
      "Server-side sessions; revoke one or all sessions",
      "TOTP two-factor authentication; recovery codes",
      "Rate-limited login; generic error messages",
      "Google OAuth sign-in",
    ],
    "Better Auth.",
  ],
  [
    "OL-9",
    "story",
    "Organisations, memberships and invitations",
    "OL-E2",
    "highest",
    5,
    "R1",
    ["backend"],
    ["OL-8"],
    "Multi-tenant: every user belongs to one or more organisations; data is isolated per organisation.",
    [
      "Create organisation; creator becomes Owner",
      "Invite by email with a role; accept invitation",
      "Switch active organisation",
      "Every query scoped by organisation (enforced in a single data-access layer, covered by tests)",
    ],
    "",
  ],
  [
    "OL-10",
    "story",
    "Roles and permissions (RBAC)",
    "OL-E2",
    "highest",
    5,
    "R1",
    ["backend", "security"],
    ["OL-9"],
    "Owner, Admin, Manager, Labeller, Reviewer, Viewer, API client, with per-project overrides.",
    [
      "Single permissions module: `can(user, action, resource)`",
      "Every API route checks permissions through it",
      "Tests for each role × action, including denials",
    ],
    "",
  ],
  [
    "OL-11",
    "story",
    "Projects",
    "OL-E2",
    "high",
    3,
    "R1",
    ["backend", "frontend"],
    ["OL-10"],
    "Create and configure labelling projects.",
    [
      "Create project with name, modality and task",
      "Project settings page",
      "Project members with roles",
      "List projects with counts",
    ],
    "",
  ],
  [
    "OL-12",
    "story",
    "Audit log",
    "OL-E2",
    "high",
    3,
    "R1",
    ["backend", "security"],
    ["OL-7"],
    "Append-only record of every significant action.",
    [
      "Audit events written in the same transaction as the change",
      "Actor, action, resource, time, IP, request ID",
      "Admin view with filters and CSV export",
      "No update or delete path for audit rows",
    ],
    "",
  ],

  // ---- E3 assets
  [
    "OL-13",
    "story",
    "Storage adapter: local disk and S3-compatible",
    "OL-E3",
    "highest",
    3,
    "R1",
    ["backend"],
    ["OL-5"],
    "One interface for object storage; local disk and S3/MinIO implementations.",
    [
      "`put`, `get`, `head`, `delete`, `signedUrl` interface",
      "Content-addressed keys (sha256)",
      "Contract tests run against both implementations",
    ],
    "",
  ],
  [
    "OL-14",
    "story",
    "Asset upload with hashing and deduplication",
    "OL-E3",
    "highest",
    5,
    "R1",
    ["backend", "frontend"],
    ["OL-11", "OL-13"],
    "Upload images (and later audio/video) into a project.",
    [
      "Drag-and-drop multi-file upload with progress",
      "sha256 computed; exact duplicates detected and linked, not stored twice",
      "Image metadata extracted (width, height, EXIF orientation)",
      "Assets list with thumbnails and status",
    ],
    "",
  ],
  [
    "OL-15",
    "story",
    "Signed media URLs",
    "OL-E3",
    "high",
    2,
    "R1",
    ["backend", "security"],
    ["OL-13"],
    "Media served only through short-lived signed URLs after a permission check.",
    ["URLs expire (default 15 min)", "Permission checked before signing"],
    "",
  ],
  [
    "OL-16",
    "story",
    "Bulk import (ZIP, folder, S3 prefix) with existing labels",
    "OL-E3",
    "medium",
    5,
    "R1",
    ["backend"],
    ["OL-14"],
    "Import many assets and, optionally, existing labels in COCO, docTR or JSONL.",
    ["Import runs as a background job with progress", "Report of imported, skipped and failed items"],
    "",
  ],

  // ---- E4 taxonomy
  [
    "OL-17",
    "story",
    "Versioned taxonomy with descriptions and guidelines",
    "OL-E4",
    "highest",
    8,
    "R1",
    ["backend", "frontend"],
    ["OL-11"],
    "A project's labels: stable key, name, description, colour, shortcut, region type, guidelines with examples.",
    [
      "Create/edit labels; every change creates a new taxonomy version with a changelog",
      "Guidelines (rich text + example images) shown in the editor",
      "Deprecate a label without deleting history",
      "Annotations record the taxonomy version they were made under",
    ],
    "",
  ],
  [
    "OL-18",
    "story",
    "Label attributes and validation rules",
    "OL-E4",
    "high",
    5,
    "R1",
    ["backend", "frontend"],
    ["OL-17"],
    "Typed attributes per label and regex/charset validation.",
    ["Attribute types: enum, number, text, boolean", "Validation warnings shown on save"],
    "",
  ],
  [
    "OL-19",
    "story",
    "Default document taxonomy template",
    "OL-E4",
    "medium",
    2,
    "R1",
    ["backend"],
    ["OL-17"],
    "Ship the default document taxonomy (architecture section 13.5) as a template.",
    ["New document projects can start from the template"],
    "",
  ],

  // ---- E5 OCR labelling
  [
    "OL-20",
    "story",
    "Canvas editor: view, zoom, pan, boxes and polygons",
    "OL-E5",
    "highest",
    8,
    "R1",
    ["frontend"],
    ["OL-14", "OL-17"],
    "react-konva canvas showing the full original image with editable regions.",
    [
      "Zoom, pan, fit-to-screen",
      "Draw, move, resize, rotate, delete boxes; polygon tool",
      "Smooth with 5,000 boxes",
      "Keyboard shortcuts for every action",
    ],
    "",
  ],
  [
    "OL-21",
    "story",
    "Word/line text editing panel",
    "OL-E5",
    "highest",
    5,
    "R1",
    ["frontend"],
    ["OL-20"],
    "Side panel with zoomed crop, text field, model suggestion and confidence.",
    [
      "Enter = accept, Tab = next, type to fix",
      "Split and merge boxes",
      "Line view; clicking a line selects its words",
    ],
    "",
  ],
  [
    "OL-22",
    "story",
    "Layers, image tags, non-text regions, flags, relations, ignore regions",
    "OL-E5",
    "high",
    8,
    "R1",
    ["frontend", "backend"],
    ["OL-20"],
    "Everything in architecture section 13.",
    [
      "Layers panel: show/hide/lock per class",
      "Auto-detected overlaps prompt for a relation",
      "Ignore regions stored and respected by export and evaluation",
    ],
    "",
  ],
  [
    "OL-23",
    "story",
    "Pre-labelling via the /predict contract",
    "OL-E5",
    "highest",
    5,
    "R1",
    ["backend"],
    ["OL-20", "OL-26"],
    "Background job calls a configured model backend and stores predictions (never ground truth).",
    [
      "Model backend registered per project",
      "Predictions stored with model version",
      "Re-run OCR on a selected box",
    ],
    "",
  ],
  [
    "OL-24",
    "story",
    "Annotation versioning and review workflow",
    "OL-E5",
    "highest",
    5,
    "R1",
    ["backend", "frontend"],
    ["OL-21"],
    "Append-only annotation versions; draft → submitted → approved/rejected.",
    ["Every save creates a new version", "Reviewer approve/reject with reason", "Compare two versions"],
    "",
  ],
  [
    "OL-25",
    "story",
    "Work queues sorted by confidence",
    "OL-E5",
    "high",
    3,
    "R1",
    ["backend", "frontend"],
    ["OL-23"],
    "Next-item queue with locking, lowest confidence first.",
    ["Two users never receive the same asset", "Abandoned locks expire"],
    "",
  ],
  [
    "OL-26",
    "task",
    "Job queue in Postgres (pg-boss) and worker app",
    "OL-E5",
    "highest",
    3,
    "R1",
    ["backend", "infra"],
    ["OL-7"],
    "Background jobs for pre-labelling, export and evaluation.",
    ["Worker processes jobs with retries and backoff", "Job status visible in the UI"],
    "",
  ],

  // ---- E6 snapshots/adapters
  [
    "OL-27",
    "story",
    "Snapshots: freeze approved annotations with a split",
    "OL-E6",
    "highest",
    5,
    "R1",
    ["backend"],
    ["OL-24"],
    "Immutable dataset versions with train/val/test split by asset.",
    [
      "Snapshot pins exact annotation versions and taxonomy version",
      "Split by asset, never by region",
      "Leakage check",
    ],
    "",
  ],
  [
    "OL-28",
    "story",
    "Adapter framework: exporter, destination, launcher, tracker",
    "OL-E6",
    "highest",
    8,
    "R1",
    ["backend"],
    ["OL-27"],
    "Interfaces plus a shared contract test kit.",
    ["Four interfaces documented", "Contract test kit every adapter must pass"],
    "",
  ],
  [
    "OL-29",
    "story",
    "First adapters: docTR, HF Parquet, JSONL; local, S3, HF Hub, Kaggle; local GPU, Kaggle; MLflow",
    "OL-E6",
    "high",
    8,
    "R1",
    ["backend"],
    ["OL-28"],
    "Initial set of adapters from architecture section 15 step 4.",
    ["Each passes the contract test kit", "Exporter output validated by loading it in the target library"],
    "",
  ],

  // ---- E7 evaluation
  [
    "OL-30",
    "story",
    "OCR engine adapters + declarative JSON mapping",
    "OL-E7",
    "high",
    8,
    "R1",
    ["backend"],
    ["OL-5"],
    "Adapters converting engine responses to the canonical OCR result.",
    [
      "docTR, Tesseract, Azure DI, Google Vision, AWS Textract",
      "Declarative mapping for any JSON API",
      "Raw responses stored; coordinate/confidence normalisation tested",
    ],
    "",
  ],
  [
    "OL-31",
    "story",
    "Matcher and metrics",
    "OL-E7",
    "highest",
    8,
    "R1",
    ["backend"],
    ["OL-5"],
    "Spatial matching + CER, WER, detection F1, end-to-end, fields, calibration, with confidence intervals.",
    ["Golden fixtures with hand-computed expected values", "Normalisation profiles versioned"],
    "",
  ],
  [
    "OL-32",
    "story",
    "Evaluation runs, leaderboard, slices, error explorer",
    "OL-E7",
    "high",
    8,
    "R1",
    ["backend", "frontend"],
    ["OL-30", "OL-31", "OL-27"],
    "Run any engine on a benchmark snapshot and explore results.",
    [
      "Leaderboard with cost and latency",
      "Slices by tag/flag",
      "Error explorer overlays errors on the canvas",
    ],
    "",
  ],
  [
    "OL-33",
    "story",
    "Regression gate API for CI",
    "OL-E7",
    "medium",
    3,
    "R1",
    ["backend"],
    ["OL-32"],
    "Fail a CI check when a model gets worse on a protected slice.",
    ["Endpoint returns pass/fail with the metric diff"],
    "",
  ],

  // ---- E8 API
  [
    "OL-34",
    "story",
    "Public REST API v1 with OpenAPI generated from zod",
    "OL-E8",
    "high",
    5,
    "R1",
    ["backend"],
    ["OL-10"],
    "Versioned API and generated documentation.",
    ["OpenAPI document served at /api/v1/openapi.json", "Docs UI"],
    "",
  ],
  [
    "OL-35",
    "story",
    "API keys and rate limiting",
    "OL-E8",
    "high",
    3,
    "R1",
    ["backend", "security"],
    ["OL-34"],
    "Scoped, expiring keys stored hashed.",
    ["Key shown once", "Per-key and per-IP rate limits"],
    "",
  ],

  // ---- E9 work management
  [
    "OL-36",
    "story",
    "Progress dashboard and per-person stats",
    "OL-E9",
    "high",
    5,
    "R1",
    ["frontend", "backend"],
    ["OL-24"],
    "Project progress by status over time; items/hour, rejection rate per person.",
    ["Burndown chart", "Per-person table"],
    "",
  ],
  [
    "OL-37",
    "story",
    "Comments and in-app notifications",
    "OL-E9",
    "medium",
    5,
    "R1",
    ["frontend", "backend"],
    ["OL-24"],
    "Threaded comments on assets/regions with @mentions.",
    ["Notifications for assignment, rejection, mention"],
    "",
  ],
];

mkdirSync(join(ROOT, "epics"), { recursive: true });
const yamlList = (a) => (a.length ? `[${a.join(", ")}]` : "[]");

for (const [key, title, release, desc] of epics) {
  const f = join(ROOT, "epics", `${key}.md`);
  if (existsSync(f)) continue;
  const children =
    T.filter((t) => t[3] === key)
      .map((t) => `- ${t[0]}: ${t[2]}`)
      .join("\n") || "- (to be broken down)";
  writeFileSync(
    f,
    `---\nkey: ${key}\ntype: epic\ntitle: ${title}\nstatus: ${release === "R0" ? "in-progress" : "todo"}\nrelease: ${release}\ncreated: ${TODAY}\nupdated: ${TODAY}\n---\n\n## Description\n\n${desc}\n\n## Issues\n\n${children}\n\n## Activity\n\n- ${TODAY}: created.\n`,
  );
}

for (const [key, type, title, epic, priority, points, release, labels, deps, desc, ac, notes] of T) {
  const f = join(ROOT, `${key}.md`);
  if (existsSync(f)) continue;
  const status = release === "R0" ? "todo" : "backlog";
  writeFileSync(
    f,
    `---\nkey: ${key}\ntype: ${type}\ntitle: ${JSON.stringify(title)}\nepic: ${epic}\nstatus: ${status}\npriority: ${priority}\npoints: ${points}\nrelease: ${release}\nlabels: ${yamlList(labels)}\ndepends_on: ${yamlList(deps)}\nassignee: \ncreated: ${TODAY}\nupdated: ${TODAY}\n---\n\n## Description\n\n${desc}\n\n## Acceptance criteria\n\n${ac.map((a) => `- [ ] ${a}`).join("\n")}\n\n## Technical notes\n\n${notes || "-"}\n\n## Activity\n\n- ${TODAY}: created (status: ${status}).\n`,
  );
}
console.log(`epics: ${epics.length}, issues: ${T.length}`);
